cout<<"\n\t\t\t\t\tBONJOUR"
	cout<<"\n\t\t\t     Quelle operation voulez vous ?"
	cout<<"\t\t1 - Rechreche Sequentielle dans un tableau non triee ; "
	cout<<"\t\t2 - Rechreche Sequentielle dans un tableau triee ; "
	cout<<"\t\t3 - Rechreche Dichotomique dans un tableau triee ; "
	cout<<"\t\t4 - Insertion dans un tableau triee ; "
	cout<<"\t\t5 - Insertion dans un tableau non triee ; "
	cout<<"\t\t6 - Supression dans un tableau triee ; "
	cout<<"\t\t7 - Tri d'un tableau 'Methode Sequentielle' ; "
	cout<<"\t\t8 - Tri d'un tableau 'Methode Dichotomique' ; "
	cout<<"\t\t9 - Tri d'un tableau 'Tri rapide' ; "
	cout<<"\n\t\t\t\t\t";
